### ISSUE TITLE
Suche: Filterfunktion

### ISSUE THREAD

**Issue by KristinaRichts** [Detmolder-Hoftheater/TheaterTool#20]
Es ist sehr irritierend, dass eine Suchabfrage ohne Nutzung der Filterfunktion keinerlei Ergebnisse liefert, man also den Filter zwingend nutzen muss. Ich hätte hier eher eine ungefilterte Ergebnisliste erwartet.

**Comment by elena1113** [comment]
fixed with commit 2a48343615a669e01345a364e9391579e72f22c8
