### ISSUE TITLE
Einnahmen: Anzeige

### ISSUE THREAD

**Issue by Irmlind** [Detmolder-Hoftheater/TheaterTool#23]
Die Einnahmen 1846 haben für das Datum zwei Felder, eines für den Monat und eines für den Tag. Bisher wird nur Feld 1 angezeigt. Feld 2 ist bislang nicht als Datum ausgezeichnet. Ist das nötig, um es anzuzeigen?
Ich habe es probiert: Ich kann nicht das Datums-Element um beide Zellen schachteln.

Vor dem endgültigen Bearbeiten bitte noch einmal Rückfragen. Dann prüfe ich, ob auch andere Jahre betroffen sind.

**Comment by elena1113** [comment]
fixed with commit a7e09c4a7ae9b52c4a33c9f476f92f9560025be7
