### ISSUE TITLE
Datum bei Theaterakten

### ISSUE THREAD

**Issue by Irmlind** [Detmolder-Hoftheater/TheaterTool#25]
Wir haben bei den Einnahme- und Ausgabebelegen in der Anzeige eine Rubrik Datum, die aber nicht ausgefüllt ist. Woran liegt das? In der xml-Datei sind die Daten ausgezeichnet.

**Comment by elena1113** [comment]
fixed with commit a7e09c4a7ae9b52c4a33c9f476f92f9560025be7
