### ISSUE TITLE
Anzeige Quellen in Werkansicht

### ISSUE THREAD

**Issue by KristinaRichts** [Detmolder-Hoftheater/TheaterTool#3]
In der Werkansicht beginnt die Anzeige der verlinkten Quellen immer mit einem Komma, z.B. "Quelle: , Mus-n 16". Könnte das Komma bitte gelöscht werden?

**Comment by elena1113** [comment]
Es wurde, warscheinlich schon gefixt, da es nicht mehr reproduzierbr ist...
