### ISSUE TITLE
Suche nach Werken (Groß-/Kleinschreibung)

### ISSUE THREAD

**Issue by KristinaRichts** [Detmolder-Hoftheater/TheaterTool#42]
Die Suche nach Werken muss so umgestellt werden, dass nicht zwischen Groß- und Kleinschreibung unterschieden wird. Beispiel: Die Suche nach "Die vornehmen Wirte" liefert keinen Treffer, die Suche nach "Die Vornehmen Wirte" aber schon.

**Comment by elena1113** [comment]
fixed with commit cc693bf7440cacde67ca2bb52042b39a78869b3a
