### ISSUE TITLE
Abfrage Personen

### ISSUE THREAD

**Issue by KristinaRichts** [Detmolder-Hoftheater/TheaterTool#48]
1) Suchabfrage bitte auf persNames beschränken. Ansonsten bekommen wir auch Treffer aus den bioSummaries. 
2) Suche nach 2. Vornamen sollte ebenfalls funktionieren, so liefert z.B. die suche nach "Kiel, August" (er heißt Clemens August Kiel) keinen Treffer

**Comment by elena1113** [comment]
fixedwith commit be564163805e43da6b84d378f020111c6a9ee0b4
