### ISSUE TITLE
Werke: Angabe Werkverzeichnis

### ISSUE THREAD

**Issue by KristinaRichts** [Detmolder-Hoftheater/TheaterTool#54]
Hier steht irrtümlicherweise Werkverzeichniss

**Comment by elena1113** [comment]
Verstehe ich nicht:-o
Bitte ein Beispiel geben!

**Comment by KristinaRichts** [comment]
Werkverzeichnis wird nur mit einem s geschrieben

**Comment by elena1113** [comment]
:-

**Comment by elena1113** [comment]
:-))))))
fixed
