### ISSUE TITLE
Rolleneinträge

### ISSUE THREAD

**Issue by KristinaRichts** [Detmolder-Hoftheater/TheaterTool#8]
a) Bei der Bezeichnung "Rolenname" fehlt das zweite "l".
b) Es wäre schön, wenn die alternativen Rollennamen mit einem Zusatz (alternativ) versehen werden könnten. Ist sonst verwirrend.
c) "Beschreibung" sollte in "Rollenbeschreibung" umbenannt werden.

**Comment by elena1113** [comment]
commit 20ddc44b94861bb92162e2205fa89426705c7c14
